version: '3'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile-prod
    image: 'client_prod'
    volumes:
      - '/opt/client:/home/app/client/dist'
    env_file: prod.env
    command: npm run build
  express:
    build: express
    ports:
      - '80:3000'
    volumes:
      - '/opt/client:/home/app/server/public'
    depends_on:
      - client
      - redis
    env_file: prod.env
    command: [pm2-docker, /home/app/server/bin/www]
  redis:
    image: redis
    ports:
      - '6379'
    env_file: prod.env
    command: redis-server --appendonly yes
